# Schema for the configuration files of the Options module.

field.storage_settings.flexible_list_integer:
  type: mapping
  label: 'Flexible list (integer) settings'

field.field_settings.flexible_list_integer:
  label: 'Flexible list (integer) settings'
  type: mapping
  mapping:
    allowed_values_whitelist:
      type: sequence
      label: 'Allowed values whitelist'
      sequence:
        type: mapping
        label: 'Allowed value with label'
        mapping:
          value:
            type: integer
            label: 'Value'
          label:
            type: label
            label: 'Label'
    allowed_values_whitelist_function:
      type: string
      label: 'Allowed values whitelist function'
    allowed_values_greylist:
      type: sequence
      label: 'Allowed values whitelist'
      sequence:
        type: mapping
        label: 'Allowed value with label'
        mapping:
          value:
            type: integer
            label: 'Value'
          label:
            type: label
            label: 'Label'
    allowed_values_greylist_function:
      type: string
      label: 'Allowed values whitelist function'

field.value.flexible_list_integer:
  type: mapping
  label: 'Default value'
  mapping:
    value:
      type: integer
      label: 'Value'

field.storage_settings.flexible_list_float:
  type: mapping
  label: 'Flexible list (float) settings'

field.field_settings.flexible_list_float:
  label: 'List (float) settings'
  type: mapping
  mapping:
    allowed_values_whitelist:
      type: sequence
      label: 'Allowed values whitelist'
      sequence:
        type: mapping
        label: 'Allowed value with label'
        mapping:
          value:
            type: float
            label: 'Value'
          label:
            type: label
            label: 'Label'
    allowed_values_whitelist_function:
      type: string
      label: 'Allowed values whitelist function'
    allowed_values_greylist:
      type: sequence
      label: 'Allowed values whitelist'
      sequence:
        type: mapping
        label: 'Allowed value with label'
        mapping:
          value:
            type: float
            label: 'Value'
          label:
            type: label
            label: 'Label'
    allowed_values_greylist_function:
      type: string
      label: 'Allowed values whitelist function'

field.value.flexible_list_float:
  type: mapping
  label: 'Default value'
  mapping:
    value:
      type: string
      label: 'Value'

field.storage_settings.flexible_list_string:
  type: mapping
  label: 'Flexible list (text) settings'

field.field_settings.flexible_list_string:
  label: 'Flexible list (text) settings'
  type: mapping
  mapping:
    allowed_values_whitelist:
      type: sequence
      label: 'Allowed values whitelist'
      sequence:
        type: mapping
        label: 'Allowed value with label'
        mapping:
          value:
            type: string
            label: 'Value'
          label:
            type: label
            label: 'Label'
    allowed_values_whitelist_function:
      type: string
      label: 'Allowed values whitelist function'
    allowed_values_greylist:
      type: sequence
      label: 'Allowed values whitelist'
      sequence:
        type: mapping
        label: 'Allowed value with label'
        mapping:
          value:
            type: string
            label: 'Value'
          label:
            type: label
            label: 'Label'
    allowed_values_greylist_function:
      type: string
      label: 'Allowed values whitelist function'

field.value.flexible_list_string:
  type: mapping
  label: 'Default value'
  mapping:
    value:
      type: string
      label: 'Value'

views.argument.flexible_list_number_field:
  type: views.argument.numeric
  mapping:
    summary:
      type: mapping
      label: 'Display a summary'
      mapping:
        sort_order:
          type: string
          label: 'Sort order'
        number_of_records:
          type: integer
          label: 'Sort by'
        format:
          type: string
          label: 'Format'
        human:
          type: boolean

views.argument.flexible_list_string_field:
  type: views.argument.string
  mapping:
    summary:
      type: mapping
      label: 'Display a summary'
      mapping:
        sort_order:
          type: string
          label: 'Sort order'
        number_of_records:
          type: integer
          label: 'Sort by'
        format:
          type: string
          label: 'Format'
        human:
          type: boolean

views.filter.flexible_list_field:
  type: views.filter.many_to_one
